name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: unzip
        run: unzip -o *.zip -d temp && cp -r temp/*/*. 2>/dev/null; cp -r temp/*. 2>/dev/null; cp -r temp/project_raw/*. 2>/dev/null; ls
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apk-jadi
          path: build/app/outputs/flutter-apk/app-release.apk
